# Generated by Django 4.0.6 on 2022-07-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasccmodel',
            old_name='excelData',
            new_name='excelFile',
        ),
    ]
