# Generated by Django 4.0.6 on 2022-07-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFiles', '0002_rename_exceldata_datasccmodel_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasccmodel',
            name='excelFile',
            field=models.FileField(upload_to='static/documents/'),
        ),
    ]
